language: csharp
os:
  - osx
  - linux

# Ubuntu 14.04
sudo: required
dist: trusty

# OS X 10.12
osx_image: xcode9.2

mono:
  - 5.10.0

dotnet: 2.1.500

# Ignore tagged commits
if: tag IS blank

script:
  - ./build.sh

cache:
  directories:
    - .packages
    - tools/Addins
    - tools/GitVersion.CommandLine